steps:
  # Build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        #"--tag=gcr.io/${_REPO_ID}/${_NAMESPACE}/${_APP_NAME}:${_DOCKER_TAG}",
        "--tag=asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}:${_DOCKER_TAG}",
        ".",
      ]

images: ["asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}"]

substitutions:
  _DOCKER_TAG: latest
  _REPOSITORY: docker-registry
  _PROJECT_ID: infinite-loop-347810
  _APP_NAME: monster-rolodex