steps:

  # Install dependencies and build for production
  - name: node:alpine
    entrypoint: npm
    args: ["install"]

  - name: node:alpine
    entrypoint: npm
    args: ["run", "build", "--if-present"]

  # Build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        #"--tag=gcr.io/${_REPO_ID}/${_NAMESPACE}/${_APP_NAME}:${_DOCKER_TAG}",
        "--tag=${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_DOCKER_TAG}",
        ".",
      ]

images: ["${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}"]

substitutions:
  _DOCKER_TAG: latest
  _LOCATION: asia-southeast1
  _REPOSITORY: docker-registry
  _PROJECT_ID: infinite-loop-347810
  _IMAGE: monster-rolodex